name: Update values.yaml from routes
on:
  push:
    branches: [ main ]
    paths:
      - 'cidm/dev/routes/**'
      - 'cidm/test/routes/**'
      - 'cidm/prod/routes/**'
  workflow_dispatch:
jobs:
  cidm-dev-update-values:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: mark generation script as executable
        run: chmod u+x generate_routes.sh
      - name: generate values.yaml from routes
        run: |
          ./generate_routes.sh cidm/dev
      - name: check for changes
        id: git-check
        run: |
          git diff --exit-code cidm/dev/routes/values.yaml || echo 'changed=true' >> $GITHUB_OUTPUT
      - name: commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add routes/values.yaml
          git commit -m 'auto-update cidm/dev/routes/values.yaml from route files [skip ci]'
          git push
      - name: no changes detected
        if: steps.git-check.outputs.changed != 'true'
        run: |
          echo 'no changes detected in routes. cidm/dev/routes/values.yaml is up to date.'
  cidm-test-update-values:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: mark generation script as executable
        run: chmod u+x generate_routes.sh
      - name: generate values.yaml from routes
        run: |
          ./generate_routes.sh cidm/test
      - name: check for changes
        id: git-check
        run: |
          git diff --exit-code cidm/test/routes/values.yaml || echo 'changed=true' >> $GITHUB_OUTPUT
      - name: commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add routes/values.yaml
          git commit -m 'auto-update cidm/test/routes/values.yaml from route files [skip ci]'
          git push
      - name: no changes detected
        if: steps.git-check.outputs.changed != 'true'
        run: |
          echo 'no changes detected in routes. cidm/test/routes/values.yaml is up to date.'
  cidm-prod-update-values:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: mark generation script as executable
        run: chmod u+x generate_routes.sh
      - name: generate values.yaml from routes
        run: |
          ./generate_routes.sh cidm/prod
      - name: check for changes
        id: git-check
        run: |
          git diff --exit-code cidm/prod/routes/values.yaml || echo 'changed=true' >> $GITHUB_OUTPUT
      - name: commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add routes/values.yaml
          git commit -m 'auto-update cidm/prod/routes/values.yaml from route files [skip ci]'
          git push
      - name: no changes detected
        if: steps.git-check.outputs.changed != 'true'
        run: |
          echo 'no changes detected in routes. routes/values.yaml is up to date.'
